# 当版本标签被推送/在github上手动创建release时触发

name: Release

on:
  push:
    tags:
      - V*.*
      - v*.*

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      # 使用标签名作为版本号
      version: ${{ github.ref_name }}

  release:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          path: release/
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            release/*
          target_commitish: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
