name: Reusable Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      # 签出代码
      - name: Checkout
        uses: actions/checkout@main

      # 配置 uv 
      - name: Setup UV for Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/uv.lock

      # 安装依赖
      - name: Install dependencies
        run: |
          uv sync --frozen

      # 注入版本号
      - name: Inject version number
        run: |
          $filePath = "assets/config/version.txt"
          "${{ inputs.version }}" | Set-Content $filePath

      # 生成 .qm 翻译文件
      - name: Generate .qm translation file
        run: |
          # 使用 PowerShell 批量处理所有 .ts 文件
          Get-ChildItem -Path .\i18n\*.ts | ForEach-Object {
              $qmPath = ".\i18n\$($_.BaseName).qm"
              uv run pyside6-lrelease $_.FullName -qm $qmPath
              Write-Host "Generated: $qmPath"
          }


      # 打包项目
      - name: Build executable & Bundle resources
        run: |
          uv run pyinstaller main.spec
          uv run pyinstaller -F -i .\assets\logo\Updater.ico -n "AALC Updater" --exclude-module numpy --exclude-module pandas updater.py -y
          mkdir dist_release
          mv dist/* dist_release/
          cp dist_release/"AALC Updater"* dist_release/AALC/
          cp -r 3rdparty dist_release/AALC/
          cp -r assets dist_release/AALC/
          mkdir dist_release/AALC/i18n
          mv i18n/*.qm dist_release/AALC/i18n/
          cp LICENSE dist_release/AALC/
          cp README.md dist_release/AALC/
          cd dist_release
          7z a -mx=7 AALC_${{ inputs.version }}.7z AALC/*
          cd ..


      # 上传打包结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@main
        with:
          name: AALC_${{ inputs.version }}
          path: |
            dist_release/AALC_${{ inputs.version }}.7z
